packages:
  - "apps/*"
  - "packages/*"
  - "packages/connectors/*"
overrides:
  vite: 6.4.3
allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  prisma: true
  esbuild: false
  sharp: false
  unrs-resolver: false
