-- Migration: add_fiber_plan
-- Fiber optic plan viewer: plans, logical zones, and interactive markers.
-- Georeferencing strategy: operator-defined logical zones (no GPS required).
-- NOTE: id columns use TEXT without DEFAULT — cuid() is generated by the application
-- (Prisma client) at insert time, matching the @default(cuid()) in schema.prisma.

-- 1. FiberPlan: metadata for an uploaded plan image or PDF.
CREATE TABLE "fiber_plans" (
    id              VARCHAR(30) NOT NULL PRIMARY KEY,
    tenant_id       VARCHAR(30) NOT NULL,
    connection_id   VARCHAR(30),
    name            VARCHAR(255) NOT NULL,
    description     TEXT,
    file_url        TEXT NOT NULL,
    mime_type       VARCHAR(100) NOT NULL,
    width_px        INTEGER,
    height_px       INTEGER,
    file_size_bytes BIGINT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX "fiber_plans_tenant_id_idx"          ON "fiber_plans"("tenant_id");
CREATE INDEX "fiber_plans_connection_id_idx"       ON "fiber_plans"("connection_id");

-- 2. PlanZone: a logical zone within a plan (e.g. "Zona Norte", "Barrio El Progreso").
CREATE TABLE "plan_zones" (
    id          VARCHAR(30) NOT NULL PRIMARY KEY,
    tenant_id   VARCHAR(30) NOT NULL,
    plan_id     VARCHAR(30) NOT NULL,
    name        VARCHAR(255) NOT NULL,
    description TEXT,
    color       VARCHAR(7) NOT NULL DEFAULT '#6366F1',
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX "plan_zones_tenant_id_idx" ON "plan_zones"("tenant_id");
CREATE INDEX "plan_zones_plan_id_idx"   ON "plan_zones"("plan_id");

-- 3. PlanMarker: a pin placed on the plan, optionally tied to a topology node.
CREATE TABLE "plan_markers" (
    id          VARCHAR(30) NOT NULL PRIMARY KEY,
    tenant_id   VARCHAR(30) NOT NULL,
    zone_id     VARCHAR(30),
    label       VARCHAR(255) NOT NULL,
    device_kind VARCHAR(20),
    device_id   VARCHAR(255),
    x_percent   FLOAT NOT NULL,
    y_percent   FLOAT NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX "plan_markers_tenant_id_idx"   ON "plan_markers"("tenant_id");
CREATE INDEX "plan_markers_zone_id_idx"     ON "plan_markers"("zone_id");
CREATE INDEX "plan_markers_device_kind_idx" ON "plan_markers"("device_kind");
CREATE INDEX "plan_markers_device_id_idx"  ON "plan_markers"("device_id");
